group:
  repos: |
    audaciaconsulting/Audacia.Log
    audaciaconsulting/Audacia.Commands
    audaciaconsulting/Audacia.DataAccess
    audaciaconsulting/Audacia.Seed
    audaciaconsulting/Audacia.Auth
    audaciaconsulting/Audacia.Mail
  files:
    - source: templates/dependabot.yaml
      dest: .github/dependabot.yaml
    - source: templates/dependabot-checklist.yaml
      dest: .github/workflows/dependabot-checklist.yaml
    - source: templates/CODEOWNERS
      dest: .github/CODEOWNERS
