name: Sync Dependabot Config

on:
  push:
    branches: [main]
    paths:
      - "templates/dependabot.yaml"
      - ".github/sync.yaml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ORG_SYNC_PAT }}
          CONFIG_PATH: .github/sync.yaml
